export const ADD_PRODUCT = "ADD_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const CALCULATE_CART = "CALCULATE_CART";
export const CALCULATE_CART_SUCCESS = "CALCULATE_CART_SUCCESS";
export const CALCULATE_CART_FAILURE = "CALCULATE_CART_FAILURE";
export const RESET_CART_DATA = "RESET_CART_DATA";
